version: '3.8'

volumes:
  nccrd_next:
    driver: local

networks:
  nccrd_next:
    name: nccrd_next
    driver: overlay
    attachable: true

services:
  nginx:
    image: $NGINX_IMAGE
    deploy:
      placement:
        constraints:
          - node.labels.service == apps
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: "1"
          memory: 150M
    ports:
      - 7006:80
    networks:
      - nccrd_next

  nccrd:
    image: $NCCRD_IMAGE
    deploy:
      placement:
        constraints:
          - node.labels.service == apps
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 15s
    volumes:
      - nccrd_next:/nccrd-assets
    environment:
      FILES_DIRECTORY: /nccrd-assets
      LOG_REQUEST_DETAILS: 'false'
      LOG_SQL_QUERIES: 'false'
      MSSQL_DATABASE: nccrd_next
      MSSQL_HOSTNAME: 192.168.118.194
      MSSQL_PASSWORD: $MSSQL_PASSWORD
      MSSQL_PORT: 1433
      MSSQL_USERNAME: $MSSQL_USERNAME
      DEFAULT_ADMIN_EMAIL_ADDRESSES: ''
      DEFAULT_SYSADMIN_EMAIL_ADDRESSES: zd.smith@saeon.nrf.ac.za
      DEPLOYMENT_ENV: production
      HOSTNAME: https://nccrd.saeon.ac.za
      SSL_ENV: production
      ODP_AUTH_CLIENT_SECRET: $ODP_AUTH_CLIENT_SECRET
    networks:
      - nccrd_next
