# Build client
FROM node:14.17.0 as client

ARG NCCRD_DEPLOYMENT_ENV
ARG NCCRD_CLIENT_DEFAULT_NOTICES
ARG NCCRD_TECHNICAL_CONTACT
ARG NCCRD_API_ADDRESS

WORKDIR /app

RUN echo "" > .env
RUN echo "NCCRD_DEPLOYMENT_ENV=$NCCRD_DEPLOYMENT_ENV" >> .env
RUN echo "NCCRD_CLIENT_DEFAULT_NOTICES=$NCCRD_CLIENT_DEFAULT_NOTICES" >> .env
RUN echo "NCCRD_TECHNICAL_CONTACT=$NCCRD_TECHNICAL_CONTACT" >> .env
RUN echo "NCCRD_API_ADDRESS=$NCCRD_API_ADDRESS" >> .env

COPY src/client .
RUN npm ci --only=production
RUN npm run build




# Start API
FROM node:14.17-alpine

ARG SAEON_AUTH_CLIENT_ID
ENV SAEON_AUTH_CLIENT_ID=$SAEON_AUTH_CLIENT_ID

ARG SAEON_AUTH_CLIENT_SCOPES
ENV SAEON_AUTH_CLIENT_SCOPES=$SAEON_AUTH_CLIENT_SCOPES

ARG SAEON_AUTH_CLIENT_SECRET
ENV SAEON_AUTH_CLIENT_SECRET=$SAEON_AUTH_CLIENT_SECRET

ARG NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES
ENV NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES=$NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES

ARG NCCRD_DEPLOYMENT_ENV
ENV NCCRD_DEPLOYMENT_ENV=$NCCRD_DEPLOYMENT_ENV

ARG NCCRD_API_NODE_ENV
ENV NCCRD_API_NODE_ENV=$NCCRD_API_NODE_ENV

ARG MSSQL_USERNAME
ENV MSSQL_USERNAME=$MSSQL_USERNAME

ARG MSSQL_PASSWORD
ENV MSSQL_PASSWORD=$MSSQL_PASSWORD

ARG MSSQL_HOSTNAME
ENV MSSQL_HOSTNAME=$MSSQL_HOSTNAME

ARG MSSQL_DATABASE
ENV MSSQL_DATABASE=$MSSQL_DATABASE

ARG MSSQL_PORT
ENV MSSQL_PORT=$MSSQL_PORT

ARG NCCRD_API_ADDRESS
ENV NCCRD_API_ADDRESS=$NCCRD_API_ADDRESS

WORKDIR /app
COPY src/api .
COPY --from=client /app/dist src/http/web/dist
RUN npm ci --only=production
EXPOSE 3000


CMD \
  SAEON_AUTH_CLIENT_ID=$SAEON_AUTH_CLIENT_ID \
  SAEON_AUTH_CLIENT_SCOPES=$SAEON_AUTH_CLIENT_SCOPES \
  SAEON_AUTH_CLIENT_SECRET=$SAEON_AUTH_CLIENT_SECRET \
  NCCRD_API_ADDRESS=$NCCRD_API_ADDRESS \
  NCCRD_DEPLOYMENT_ENV=$NCCRD_DEPLOYMENT_ENV \
  NCCRD_API_NODE_ENV=$NCCRD_API_NODE_ENV \
  NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES=$NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES \
  MSSQL_USERNAME=$MSSQL_USERNAME \
  MSSQL_PASSWORD=$MSSQL_PASSWORD \
  MSSQL_HOSTNAME=$MSSQL_HOSTNAME \
  MSSQL_DATABASE=$MSSQL_DATABASE \
  MSSQL_PORT=$MSSQL_PORT \
  npm run start:prod