import json from '@rollup/plugin-json'

export default {
  input: 'src/index.js',
  external: [
    'xlsx-populate',
    'stream',
    'apollo-server-core',
    'object-hash',
    'http',
    'koa',
    'koa-static',
    'koa-mount',
    '@koa/router',
    'koa2-formidable',
    'koa-compress',
    'koa-bodyparser',
    'koa-session',
    'koa-passport',
    'zlib',
    'path',
    'nanoid',
    'base64url',
    'apollo-server-koa',
    'node-fetch',
    'openid-client',
    'dotenv',
    'url',
    'fs',
    'mssql',
    'graphql-tools',
    'dataloader',
    'sift',
    'sql-formatter',
    'graphql-type-json',
    'graphql',
    'graphql/language/printer.js',
    'wkt',
    'csv',
    'perf_hooks',
  ],
  output: {
    file: 'bin/index.cjs',
    format: 'cjs',
  },
  plugins: [json()],
}
