version: '3.9'

networks:
  nccrd_stable:
    name: nccrd_stable
    driver: overlay
    attachable: true

services:
  nginx:
    image: $NGINX_IMAGE
    deploy:
      placement:
        constraints:
          - node.labels.service == apps
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          cpus: "2"
          memory: 250M
    ports:
      - 7007:80
    networks:
      - nccrd_stable

  nccrd:
    image: $NCCRD_IMAGE
    deploy:
      placement:
        constraints:
          - node.labels.service == apps
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          cpus: "2"
          memory: 250M
    volumes:
      - type: bind
        source: /mnt/nccrd/data/stable
        target: /nccrd-assets
    environment:
      FILES_DIRECTORY: /nccrd-assets
      LOG_REQUEST_DETAILS: 'false'
      LOG_SQL_QUERIES: 'false'
      MSSQL_DATABASE: nccrd_stable
      MSSQL_HOSTNAME: mssql.saeon.int
      MSSQL_PASSWORD: $MSSQL_PASSWORD
      MSSQL_PORT: 1433
      MSSQL_USERNAME: $MSSQL_USERNAME
      DEFAULT_ADMIN_EMAIL_ADDRESSES: 'TMakholela@environment.gov.za,tmakholela@yahoo.com,rditlopo@environment.gov.za'
      DEFAULT_SYSADMIN_EMAIL_ADDRESSES: zd.smith@saeon.nrf.ac.za
      DEPLOYMENT_ENV: production
      HOSTNAME: https://nccrd.environment.gov.za
      SSL_ENV: production
      ODP_AUTH_CLIENT_SECRET: $ODP_AUTH_CLIENT_SECRET
    networks:
      - nccrd_stable
