name: Deploy nccrd.saeon.ac.za

on:
  workflow_dispatch:

env:
  SWARM_HOSTNAME: ${{ secrets.SWARM_HOSTNAME }} # Organization secret
  SWARM_USERNAME: ${{ secrets.SWARM_USERNAME }} # Organization secret
  SWARM_PASSWORD: ${{ secrets.SWARM_PASSWORD }} # Organization secret
  SWARM_SSH_PORT: ${{ secrets.SWARM_SSH_PORT }} # Organization secret
  MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }} # Repository secret
  MSSQL_USERNAME: ${{ secrets.MSSQL_USERNAME }} # Repository secret
  ODP_AUTH_CLIENT_SECRET: ${{ secrets.ODP_AUTH_CLIENT_SECRET }} # Repository secret
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NCCRD_IMAGE_NAME: ${{ github.repository }}_next_node
  NGINX_IMAGE_NAME: ${{ github.repository }}_next_nginx
  REGISTRY: ghcr.io
  BRANCH_REF: next

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.NGINX_IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push NCCRD
        uses: docker/build-push-action@master
        with:
          context: src/nginx
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-nccrd:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Check out source code (shared)
        uses: actions/checkout@master
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.NCCRD_IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push NCCRD
        uses: docker/build-push-action@master
        with:
          context: .
          build-args: |
            HOSTNAME=https://nccrd.saeon.ac.za
            DEFAULT_TENANT_ADDRESS=https://nccrd.saeon.ac.za
            DEFAULT_NOTICES="This is the DEVELOPMENT deployment,warn"
            SHOW_DEV_WARNING="true"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build-nginx, build-nccrd]
    runs-on: saeon
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: (SCP) Copy Docker files to app server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SWARM_HOSTNAME }}
          username: ${{ env.SWARM_USERNAME }}
          password: ${{ env.SWARM_PASSWORD }}
          port: ${{ env.SWARM_SSH_PORT }}
          source: 'deploy/next/stack.yml'
          target: 'nccrd-next'

      - name: (SSH) Deploy Docker stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SWARM_HOSTNAME }}
          username: ${{ env.SWARM_USERNAME }}
          password: ${{ env.SWARM_PASSWORD }}
          port: ${{ env.SWARM_SSH_PORT }}
          script: |
            echo "MSSQL_PASSWORD=${{ env.MSSQL_PASSWORD }}" > /home/runner/nccrd-next/deploy/next/stack.env
            echo "MSSQL_USERNAME=${{ env.MSSQL_USERNAME }}" >> /home/runner/nccrd-next/deploy/next/stack.env
            echo "NCCRD_IMAGE=${{ needs.build-nccrd.outputs.image }}" >> /home/runner/nccrd-next/deploy/next/stack.env
            echo "NGINX_IMAGE=${{ needs.build-nginx.outputs.image }}" >> /home/runner/nccrd-next/deploy/next/stack.env
            echo "ODP_AUTH_CLIENT_SECRET=${{ env.ODP_AUTH_CLIENT_SECRET }}" >> /home/runner/nccrd-next/deploy/next/stack.env
            sudo /opt/deploy-docker-stack.sh /home/runner/nccrd-next/deploy/next/stack.yml /home/runner/nccrd-next/deploy/next/stack.env nccrd_next
