name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  pkg-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: stable

      - name: Build binaries via Docker
        run: |
          docker image build -t nccrd-binaries -f pkg.Dockerfile .

      - name: Get binaries from Docker context
        run: |
          docker cp $(docker create --rm nccrd-binaries):/app/binaries/ ./

      - name: Publish binaries
        uses: softprops/action-gh-release@master
        with:
          files: |
            binaries/nccrd-linux
            binaries/nccrd-macos
            binaries/nccrd-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
